export const cinemas = ["Movie", "TV Show", "Both"];
export const categories = [
	"Action",
	"Adventure",
	"Animation",
	"Biography",
	"Comedy",
	"Crime",
	"Documentary",
	"Drama",
	"Family",
	"Fantasy",
	"Film-Noir",
	"History",
	"Horror",
	"Musical",
	"Mystery",
	"Romance",
	"Sci-Fi",
	"Sport",
	"Thriller",
	"War",
	"Western",
	"Art-house",
	"Black-Comedy",
	"Chick-flick",
	"Cult-classic",
	"Dark-Comedy",
	"Epic",
	"Erotic",
	"Experimental",
	"Fairy-tale",
	"Film-within-a-film",
	"Futuristic",
	"Gangster",
	"Heist",
	"Historical",
	"Holiday",
	"Indie",
	"Juvenile",
	"Melodrama",
	"Monster",
	"Political",
	"Psychological",
	"Road-movie",
	"Romantic-Comedy",
	"Satire",
	"Science-Fiction",
	"Slapstick",
	"Social-issue",
	"Spy",
	"Superhero",
	"Supernatural",
	"Surreal",
	"Teen",
	"Time-Travel",
	"Vampire",
	"Werewolf",
	"Zombie",
];

export const r = [
	{
		name: "Jumanji: Welcome to the Jungle",
		imdb_id: "tt2283362",
		description:
			"Four teenagers are sucked into a magical video game, and the only way they can escape is to work together to finish the game.",
	},
	{
		name: "The Adventures of Tintin",
		imdb_id: "tt0983193",
		description:
			"Intrepid reporter Tintin and Captain Haddock set off on a treasure hunt for a sunken ship commanded by Haddock's ancestor.",
	},
	{
		name: "Indiana Jones and the Last Crusade",
		imdb_id: "tt0097576",
		description:
			"When Dr. Henry Jones Sr. suddenly goes missing while pursuing the Holy Grail, eminent archaeologist Indiana Jones must follow in his father's footsteps and stop the Nazis.",
	},
	{
		name: "",
		imdb_id: "tt0120616",
		description:
			"An American serving in the French Foreign Legion on an archaeological dig at the ancient city of Hamunaptra accidentally awakens a Mummy.",
	},
	{
		name: "LOST",
		description:
			"Queen Poppy and Branch make a surprising discovery — there are other Troll worlds beyond their own, and their distinct differences create big clashes between these various tribes.",
	},
];
